XGBoost:
  n_estimators: 363
  max_depth: 6
  learning_rate: 0.03886
  subsample: 0.7244
  colsample_bytree: 0.9127
  min_child_weight: 5       # ADD
  scale_pos_weight: 70.6   # ADD
  random_state: 42